version: '3'

services:

  webserver:
    image: 'nginx:latest'
    depends_on:
    - php
    restart: always
    ports:
      - "8000:80"
    volumes:
      - '../src/:/code'
      - './config/nginx/nginx_default_site.conf:/etc/nginx/conf.d/default.conf'

  php:
    build:
      context: ./images
      dockerfile: php-dockerfile
    container_name: php
    depends_on:
      - mysql
    restart: always
    volumes:
      - '../src/:/code'
    environment:
      DB_HOST: "mysql"
      DB_PORT: 3306
      DB_DATABASE: "${MYSQL_DATABASE}"
      DB_USERNAME: "root"
      DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  mysql:
    image: mysql:5
    container_name: mysql
    restart: always
    expose:
      - 3306
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"